from .external_functions import (insert_new_user_in_table,
                                 check_user_in_table,
                                 get_user_language,
                                 get_start_time,
                                 insert_time_again,
                                 insert_secret_kit,
                                 check_user_in_versus_table,
                                 check_user_combo_in_versus_table,
                                 insert_in_versus_table,
                                 check_secret_kit,
                                 insert_user_combo_in_versus_table,
                                 change_language,
                                 get_bot_first_attempt,
                                 insert_first_bot_combo_in_versus_table,
                                 seek_bools,
                                 append_kit,
                                 verify_when_two_cows,
                                 verify_bools_position,
                                 insert_bot_comboline_in_bot_list,
                                 return_bot_list,
                                 return_user_combo_for_bot,
                                 return_user_wins,
                                 return_total_games,
                                 return_bot_wins,
                                 reset_user_table_over_bot_pobeda,
                                 reset_versusbot_table_over_bot_pobeda,
                                 reset_time,
                                 time_counter,
                                 format_bot_response,
                                 cancel_reset_user_table,
                                 cancel_reset_versusbot_table)
from .digit_functions import *
from .solo_functions import *
